# Folders to ignore
Library/
library/
Temp/
temp/
Obj/
obj/
Build/
build/
Builds/
builds/
UserSettings/
usersettings/
MemoryCaptures/
memorycaptures/
Logs/
logs/

# Asset Store Tools
**/Assets/AssetStoreTools/
**/assets/assetstoretools/

# Plastic SCM (version control)
**/Assets/Plugins/PlasticSCM*
/assets/plugins/PlasticSCM*

# Private files
*.private
*.private.meta
^*.private.[0-9]+$
^*.private.[0-9]+.meta$

# IDE and editor files
.vs
.vscode
.idea
.gradle

# Other files to ignore
ExportedObj/
.consulo
*.csproj
*.unityproj
*.sln
*.suo
*.tmp
*.user
*.userprefs
*.pidb
*.booproj
*.svd
*.pdb
*.mdb
*.opendb
*.VC.db
*.pidb.meta
*.pdb.meta
*.mdb.meta

# Crash logs and build properties
sysinfo.txt
crashlytics-build.properties

# Built files (binaries, Unity packages)
*.apk
*.aab
*.app
*.unitypackage

# Temporary Unity files
~UnityDirMonSyncFile~*

# Addressable assets
**/Assets/AddressableAssetsData/*/*.bin*
**/assets/addressableassetsdata/*/*.bin*

# Streaming Assets
**/Assets/StreamingAssets/aa.meta
**/assets/streamingassets/*/aa/*

# System files
.DS_Store*
Thumbs.db
Desktop.ini

# Ignore PackageCache folder
Library/PackageCache/
